# example profiles.yml file
nasdaq_data:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: func_nasdaq_data_rw
      password: nasdaq
      port: 5432
      dbname: nasdaq_data
      schema: raw
      threads: 4